// <auto-generated />
namespace RainMakr.Web.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDeviceEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDeviceEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201603191202121_AddDeviceEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
